# Generated by Django 4.2.5 on 2023-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('davlat', models.CharField(max_length=30)),
                ('jins', models.CharField(blank=True, max_length=10)),
                ('tugilgan_yil', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('narx', models.PositiveBigIntegerField()),
                ('davomiylik', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('janr', models.CharField(max_length=30)),
                ('yil', models.DateField(blank=True)),
                ('aktyorlar', models.ManyToManyField(to='film.aktyor')),
            ],
        ),
    ]
